name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          debug: true
          script: |
            cd /var/www/qsee/qsee.su/
            git pull origin master
            php composer.phar install --no-interaction --prefer-dist --optimize-autoloader
            bash -c "source /home/qsee/.nvm/nvm.sh && nvm use 18 && npm ci && npm run build"
            php artisan migrate --force
            php artisan cache:clear
            php artisan config:clear
            php artisan route:clear
            php artisan view:clear
            php artisan optimize

